

# Dependencies
# markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Hyde
tagline:          'A Jekyll theme, with instant search'
description:      'The popular <a href="http://hyde.getpoole.com/" target="_blank">Hyde theme</a> for <a href="http://jekyllrb.com" target="_blank">Jekyll</a>, now with instant-search capabilities. Made by <a href="https://twitter.com/mdo" target="_blank">@mdo</a> and <a href="https://www.algolia.com/" target="_blank">Algolia</a>'
url:              https://github.com/algolia/algoliasearch-jekyll-hyde
baseurl:          /algoliasearch-jekyll-hyde
# Travis will install Bundler dependencies in ./vendor, so we need to exclude it
# otherwise Jekyll will try to build it (and fail)
exclude:          [vendor]

author:
  name:           'Algolia'
  url:            https://www.algolia.com/
# Thanks to @mdo for the original theme
# author:
#   name:           'Mark Otto'
#   url:            https://twitter.com/mdo

paginate:         5

# Custom vars
version:          2.1.0

github:
    repo:         https://github.com/algolia/algoliasearch-jekyll-hyde

# Algolia
gems:
  - algoliasearch-jekyll

algolia:
  application_id: 'MXM0JWJNIW'
  index_name: 'jekyll_v1'
  settings:
    highlightPreTag: '<span class="ajs-highlight">'
    highlightPostTag: '</span>'
    attributesToSnippet: ['text:40']
    snippetEllipsisText: '…'
    attributesToRetrieve:
      - anchor
      - date
      - text
      - title
      - url
  read_only_api_key: 'ff7b0847d8705c279222272303e68527'
  search_box_selector: '.ajs-searchbox'
  search_results_selector: '.ajs-results'
  template_result_selector: '.ajs-template-result'
